In [16]:
import pandas as pd

pd.set_option("display.notebook_repr_html", True)

truck_events = pd.read_csv("../files/input/truck_event_text_partition.csv")

print(truck_events.head())

   driverId  truckId eventTime eventType  longitude  latitude  \
0        14       25   59:21.4    Normal     -94.58     37.03
1        18       16   59:21.7    Normal     -89.66     39.78
2        27      105   59:21.7    Normal     -90.21     38.65
3        11       74   59:21.7    Normal     -90.20     38.65
4        22       87   59:21.7    Normal     -90.04     35.19

                     eventKey  CorrelationId       driverName     routeId  \
0   14|25|9223370572464814373   3.660000e+18       Adis Cesir   160405074
1   18|16|9223370572464814089   3.660000e+18        Grant Liu  1565885487
2  27|105|9223370572464814070   3.660000e+18  Mark Lochbihler  1325562373
3   11|74|9223370572464814123   3.660000e+18   Jamie Engesser  1567254452
4   22|87|9223370572464814101   3.660000e+18    Nadeem Asghar  1198242881

                                routeName      eventDate
0           Joplin to Kansas City Route 2  2016-05-27-22
1           Springfield to KC Via Hanibal  2016-05-27-22
2  Springfield to KC Via Columbia Route 2  2016-05-27-22
3           Saint Louis to Memphis Route2  2016-05-27-22
4           Saint Louis to Chicago Route2  2016-05-27-22

In [19]:
truck_events_subset = truck_events[0:10]
truck_events_subset

specific_columns = truck_events_subset[
    ["driverId", "eventTime", "eventType"]
]
specific_columns

   driverId eventTime eventType
0        14   59:21.4    Normal
1        18   59:21.7    Normal
2        27   59:21.7    Normal
3        11   59:21.7    Normal
4        22   59:21.7    Normal
5        22   59:22.3    Normal
6        23   59:22.4    Normal
7        11   59:22.5    Normal
8        20   59:22.5    Normal
9        32   59:22.5    Normal

In [20]:
# Escritura de la tabla en el disco
import os

if not os.path.exists("../files/output/"):
    os.makedirs("../files/output/")

specific_columns.to_csv(
    "../files/output/specific-columns.csv",
    sep=",",
    header=True,
    index=True,
)